import { Button, VerticalBox, GridBox, LineEdit, HorizontalBox } from "std-widgets.slint";


component AppText inherits Text {
    horizontal-alignment: center;
    font-size: 28px;
    font-weight: 700;
    color: white;   
}

component KeyboardButton inherits Rectangle {
    in property <string> text;
    in property <string> rtext;
    in property <color> bcolor;

    in-out property <bool> is_pressed: false;

    Text {
        text: text;
        horizontal-alignment: center;
        color: white;
        font-size: 16px;

    }
    border-color: bcolor;
    background: is_pressed ? white:black;
    animate background {
         duration: 200ms;
    }
    border-width: 1px;
    width: 32px; height: 32px;
}

export component AppWindow inherits Window {

    in-out property <string> char;
    in-out property <string> event;
    in-out property <bool> is_correct_event: true;

    in-out property <int> count_correct: 0;
    in-out property <int> count_incorrect: 0;

    in-out property <bool> is_main_mode: true;
    in-out property <bool> is_char_mode: false;
    in-out property <bool> is_sentence_mode: false;

    in-out property <string> correct_sentence;
    in-out property <string> input_sentence;
    in-out property <string> edit_string;
    in-out property <string> keyboard_event;
    in-out property <bool> is_correct_sentence;

    callback key_accept();

    callback sentence_accept();
    callback keyboard_key_accept();


    width: 1000px;
    height: 500px;

    VerticalBox {

        visible: is_main_mode ? true:false;

        Text {
            AppText {text: "Main";}
        }

        Button {
            text: "CharMode";

            clicked => {
                root.is_main_mode = false;
                root.is_char_mode = true;
                input_ch.focus();
            }
        }

        Button {
            text: "SentenceMode";

            clicked => {
                root.is_main_mode = false;
                root.is_sentence_mode = true;
                input_sent.focus();
            }
        }
    }

    VerticalLayout {
        visible: is_sentence_mode ? true:false;

        AppText {text: "\{root.correct_sentence}"; }

        FocusScope{
            input_sent := LineEdit {

                horizontal-alignment: center;
                font-size: 16px;
                width: 400px;
                height: 20px;
                x: 300px;
                padding: 20px;
                placeholder-text: "Enter text here";

                accepted(sentence) => {
                    root.input_sentence = sentence;
                    sentence_accept();
                    if (is_correct_sentence == true) {
                        self.text = "";
                    }
                }
                edited(edit_string) => {
                    root.edit_string = edit-string;
                    keyboard_key_accept()
                }
            }
            key-pressed(event) => {
                if (event.text == Key.Shift) {
                    root.keyboard_event = "LShift";
                }
                else if (event.text == Key.ShiftR) {
                    root.keyboard_event = "RShift";
                }
                else if (event.text == Key.Alt) {
                    root.keyboard_event = "LAlt";
                }
                else if (event.text == Key.AltGr) {
                    root.keyboard_event = "RAlt";
                }
                
                accept
            }
        }

        VerticalBox {

            x: 228px;

            HorizontalLayout {
                spacing: 5px;

                KeyboardButton {text: "`"; rtext: "Ё"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "1"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "2"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "3"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "4"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "5"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "6"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "7"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "8"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "9"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "0"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "-"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "="; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "BSpace"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 72px;}
            }
            HorizontalLayout {
                spacing: 5px;

                KeyboardButton {text: "TAB"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 56px;}
                KeyboardButton {text: "Q"; rtext: "Й"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "W"; rtext: "Ц"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "E"; rtext: "У"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "R"; rtext: "К"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "T"; rtext: "Е"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "Y"; rtext: "Н"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "U"; rtext: "Г"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "I"; rtext: "Ш"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "O"; rtext: "Щ"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "P"; rtext: "З"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "["; rtext: "Х"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "]"; rtext: "Ъ"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "\\"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 48px;}
            }
            HorizontalLayout {
                spacing: 5px;

                KeyboardButton {text: "CLock"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 70px;}
                KeyboardButton {text: "A"; rtext: "Ф"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "S"; rtext: "Ы"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "D"; rtext: "В"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "F"; rtext: "А"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "G"; rtext: "П"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "H"; rtext: "Р"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "J"; rtext: "О"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "K"; rtext: "Л"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "L"; rtext: "Д"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: ";"; rtext: "Ж"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "'"; rtext: "Э"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "Enter"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 72px;}
            }
            HorizontalLayout {
                spacing: 5px;

                KeyboardButton {text: "LShift"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 90px;}
                KeyboardButton {text: "Z"; rtext: "Я"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "X"; rtext: "Ч"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "C"; rtext: "С"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "V"; rtext: "М"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "B"; rtext: "И"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "N"; rtext: "Т"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "M"; rtext: "Ь"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: ","; rtext: "Б"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "."; rtext: "Ю"; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "/"; rtext: "."; bcolor: white; is_pressed: (self.text == keyboard_event || self.rtext == keyboard_event) ? true:false;}
                KeyboardButton {text: "RShift"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 90px;}
            }
            HorizontalLayout {
                spacing: 5px;

                KeyboardButton {text: "LCtrl"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 64px;}
                KeyboardButton {text: "Fn"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "Win"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false;}
                KeyboardButton {text: "LAlt"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 64px;}
                KeyboardButton {text: "Space"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 205px;}
                KeyboardButton {text: "RAlt"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 64px;}
                KeyboardButton {text: "RCtrl"; bcolor: white; is_pressed: (self.text == keyboard_event) ? true:false; width: 64px;}
            }
        }

        AppText {
            text: "Correct: \{root.count_correct}\nIncorrect: \{root.count_incorrect}";
        }
    
        Button {
            width: 400px;
            height: 100px;
            x: 300px;
            padding-top: 200px;
            text: "Exit";

            clicked => {
                root.is_sentence_mode = false;
                root.is_main_mode = true;
                root.sentence_accept();
            }
        }
    }
    
    VerticalBox {

        visible: is_char_mode ? true:false;
        

        AppText {
            text: "Press button:";
        }

        AppText {
            text: "\{root.char}";
            color: is_correct_event ? white:red;
            animate color {
                 duration: 250ms;
            }
        }
        
        input_ch := FocusScope {       

            key-pressed(event) => {
                root.event = event.text;
                if (event.text == Key.Shift || event.text == Key.ShiftR) {
                    root.event = "Shift";
                }
                root.key_accept();
                accept
            }
        }
        
        AppText {
            text: "Correct: \{root.count_correct}\nIncorrect: \{root.count_incorrect}";
        }

        Button {
            text: "Exit";
            height: 100px;

            clicked => {
                root.is_char_mode = false;
                root.is_main_mode = true;
                root.key_accept();
                root.is_correct_event = true;
            }
        }

    }
}